-- SQL Mastery Lab - PostgreSQL
-- Script idempotente: pode ser executado novamente para restaurar toda a base.
-- IMPORTANTE: este arquivo deve ser executado conectado ao banco sql_mastery.

BEGIN;

DROP VIEW IF EXISTS vw_customer_summary CASCADE;
DROP VIEW IF EXISTS vw_order_totals CASCADE;

DROP TABLE IF EXISTS inventory_movements CASCADE;
DROP TABLE IF EXISTS support_tickets CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

CREATE TABLE departments (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(80) NOT NULL UNIQUE,
    cost_center     varchar(20) NOT NULL UNIQUE,
    budget          numeric(14,2) NOT NULL CHECK (budget >= 0)
);

CREATE TABLE employees (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id   integer NOT NULL REFERENCES departments(id),
    manager_id      integer REFERENCES employees(id),
    name            varchar(120) NOT NULL,
    email           varchar(160) NOT NULL UNIQUE,
    role            varchar(100) NOT NULL,
    salary          numeric(12,2) NOT NULL CHECK (salary > 0),
    hire_date       date NOT NULL,
    active          boolean NOT NULL DEFAULT true
);

CREATE TABLE customers (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(120) NOT NULL,
    email           varchar(160) NOT NULL UNIQUE,
    city            varchar(100) NOT NULL,
    state           char(2) NOT NULL,
    birth_date      date,
    signup_date     date NOT NULL,
    segment         varchar(20) NOT NULL CHECK (segment IN ('bronze','silver','gold','platinum')),
    active          boolean NOT NULL DEFAULT true,
    metadata        jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE categories (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(80) NOT NULL UNIQUE
);

CREATE TABLE suppliers (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(120) NOT NULL UNIQUE,
    country         varchar(80) NOT NULL,
    rating          numeric(3,2) NOT NULL CHECK (rating BETWEEN 0 AND 5)
);

CREATE TABLE products (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     integer NOT NULL REFERENCES categories(id),
    supplier_id     integer NOT NULL REFERENCES suppliers(id),
    sku             varchar(30) NOT NULL UNIQUE,
    name            varchar(140) NOT NULL,
    price           numeric(12,2) NOT NULL CHECK (price >= 0),
    cost            numeric(12,2) NOT NULL CHECK (cost >= 0),
    stock           integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
    active          boolean NOT NULL DEFAULT true,
    attributes      jsonb NOT NULL DEFAULT '{}'::jsonb,
    tags            text[] NOT NULL DEFAULT ARRAY[]::text[]
);

CREATE TABLE orders (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     integer NOT NULL REFERENCES customers(id),
    salesperson_id  integer REFERENCES employees(id),
    order_date      timestamp NOT NULL,
    status          varchar(20) NOT NULL CHECK (status IN ('pending','paid','shipped','delivered','cancelled')),
    channel         varchar(20) NOT NULL CHECK (channel IN ('web','mobile','store','marketplace')),
    shipping_city   varchar(100) NOT NULL,
    shipping_state  char(2) NOT NULL,
    discount        numeric(5,4) NOT NULL DEFAULT 0 CHECK (discount BETWEEN 0 AND 1),
    freight         numeric(12,2) NOT NULL DEFAULT 0 CHECK (freight >= 0)
);

CREATE TABLE order_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id      integer NOT NULL REFERENCES products(id),
    quantity        integer NOT NULL CHECK (quantity > 0),
    unit_price      numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    discount        numeric(5,4) NOT NULL DEFAULT 0 CHECK (discount BETWEEN 0 AND 1),
    line_total      numeric(14,2) GENERATED ALWAYS AS
                    (round((quantity * unit_price * (1 - discount))::numeric, 2)) STORED,
    UNIQUE(order_id, product_id)
);

CREATE TABLE payments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        bigint NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
    method          varchar(20) NOT NULL CHECK (method IN ('pix','credit_card','debit_card','bank_slip')),
    paid_at         timestamp,
    amount          numeric(14,2) NOT NULL CHECK (amount >= 0),
    status          varchar(20) NOT NULL CHECK (status IN ('pending','approved','refunded','failed')),
    installments    integer NOT NULL DEFAULT 1 CHECK (installments BETWEEN 1 AND 12)
);

CREATE TABLE reviews (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     integer NOT NULL REFERENCES customers(id),
    product_id      integer NOT NULL REFERENCES products(id),
    rating          integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment         text,
    created_at      timestamp NOT NULL,
    UNIQUE(customer_id, product_id)
);

CREATE TABLE support_tickets (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     integer NOT NULL REFERENCES customers(id),
    assigned_to     integer REFERENCES employees(id),
    category        varchar(30) NOT NULL CHECK (category IN ('delivery','payment','product','return','account')),
    priority        varchar(10) NOT NULL CHECK (priority IN ('low','medium','high','urgent')),
    status          varchar(20) NOT NULL CHECK (status IN ('open','in_progress','resolved','closed')),
    opened_at       timestamp NOT NULL,
    closed_at       timestamp,
    CHECK (closed_at IS NULL OR closed_at >= opened_at)
);

CREATE TABLE inventory_movements (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      integer NOT NULL REFERENCES products(id),
    movement_type   varchar(12) NOT NULL CHECK (movement_type IN ('IN','OUT','ADJUSTMENT')),
    quantity        integer NOT NULL CHECK (quantity <> 0),
    occurred_at     timestamp NOT NULL,
    note            varchar(200)
);

-- Dados de referência --------------------------------------------------------
INSERT INTO departments (id, name, cost_center, budget) VALUES
(1, 'Diretoria',      'CC-001', 1200000.00),
(2, 'Vendas',         'CC-100',  850000.00),
(3, 'Operações',      'CC-200',  720000.00),
(4, 'Tecnologia',     'CC-300', 1100000.00),
(5, 'Atendimento',    'CC-400',  560000.00);

INSERT INTO employees (id, department_id, manager_id, name, email, role, salary, hire_date, active) VALUES
(1,  1, NULL, 'Ana Martins',       'ana.martins@sqlmastery.local',       'CEO',                    32000.00, '2017-02-10', true),
(2,  2, 1,    'Bruno Alves',       'bruno.alves@sqlmastery.local',       'Gerente de Vendas',      18500.00, '2018-04-02', true),
(3,  3, 1,    'Carla Ribeiro',     'carla.ribeiro@sqlmastery.local',     'Gerente de Operações',   17800.00, '2018-08-13', true),
(4,  4, 1,    'Diego Lima',        'diego.lima@sqlmastery.local',        'Gerente de Tecnologia',  22000.00, '2019-01-07', true),
(5,  5, 1,    'Elisa Fernandes',   'elisa.fernandes@sqlmastery.local',   'Gerente de Atendimento', 16500.00, '2019-03-18', true),
(6,  2, 2,    'Felipe Rocha',      'felipe.rocha@sqlmastery.local',      'Executivo de Contas',     9200.00, '2020-06-15', true),
(7,  2, 2,    'Gabriela Nunes',    'gabriela.nunes@sqlmastery.local',    'Executiva de Contas',     9600.00, '2021-01-11', true),
(8,  2, 2,    'Henrique Souza',    'henrique.souza@sqlmastery.local',    'Executivo de Contas',     8800.00, '2022-05-09', true),
(9,  2, 2,    'Isabela Costa',     'isabela.costa@sqlmastery.local',     'Analista Comercial',      6700.00, '2023-02-06', true),
(10, 3, 3,    'João Mendes',       'joao.mendes@sqlmastery.local',       'Analista de Logística',   7200.00, '2020-11-23', true),
(11, 3, 3,    'Karen Freitas',     'karen.freitas@sqlmastery.local',     'Analista de Estoque',     6900.00, '2022-09-05', true),
(12, 4, 4,    'Lucas Barros',      'lucas.barros@sqlmastery.local',      'Desenvolvedor Backend',  12800.00, '2021-07-19', true),
(13, 4, 4,    'Mariana Prado',     'mariana.prado@sqlmastery.local',     'DBA',                    14900.00, '2020-02-17', true),
(14, 4, 4,    'Nicolas Cardoso',   'nicolas.cardoso@sqlmastery.local',   'Analista de Dados',      11800.00, '2022-04-04', true),
(15, 5, 5,    'Olivia Teixeira',   'olivia.teixeira@sqlmastery.local',   'Analista de Suporte',     5900.00, '2023-03-20', true),
(16, 5, 5,    'Paulo Monteiro',    'paulo.monteiro@sqlmastery.local',    'Analista de Suporte',     6100.00, '2021-10-25', true),
(17, 5, 5,    'Quezia Lopes',      'quezia.lopes@sqlmastery.local',      'Analista de CX',          6500.00, '2022-12-12', true),
(18, 3, 3,    'Rafael Dias',       'rafael.dias@sqlmastery.local',       'Assistente de Operações', 4800.00, '2024-01-15', false);

INSERT INTO categories (id, name) VALUES
(1, 'Eletrônicos'), (2, 'Casa'), (3, 'Escritório'), (4, 'Esportes'),
(5, 'Livros'), (6, 'Games'), (7, 'Beleza'), (8, 'Acessórios');

INSERT INTO suppliers (id, name, country, rating) VALUES
(1, 'Nova Tech',       'Brasil',       4.75),
(2, 'Casa Viva',       'Brasil',       4.30),
(3, 'Office One',      'Brasil',       4.55),
(4, 'Motion Gear',     'Estados Unidos', 4.60),
(5, 'Editora Horizonte','Brasil',      4.90),
(6, 'Pixel Forge',     'Japão',        4.80),
(7, 'Belle Care',      'França',       4.45),
(8, 'Urban Carry',     'Brasil',       4.20),
(9, 'Andes Imports',   'Chile',        3.95),
(10,'Global Source',   'China',        4.10);

-- Clientes: 80 registros determinísticos.
INSERT INTO customers (id, name, email, city, state, birth_date, signup_date, segment, active, metadata)
SELECT
    i,
    'Cliente ' || lpad(i::text, 3, '0'),
    'cliente' || lpad(i::text, 3, '0') || '@exemplo.com',
    (ARRAY['São Paulo','Campinas','Rio de Janeiro','Niterói','Belo Horizonte','Curitiba','Porto Alegre','Salvador','Recife','Florianópolis'])[((i - 1) % 10) + 1],
    (ARRAY['SP','SP','RJ','RJ','MG','PR','RS','BA','PE','SC'])[((i - 1) % 10) + 1],
    DATE '1968-01-01' + ((i * 173) % 12500),
    DATE '2021-01-01' + ((i * 29) % 1460),
    (ARRAY['bronze','silver','gold','platinum'])[((i - 1) % 4) + 1],
    (i % 11 <> 0),
    jsonb_build_object(
        'source', (ARRAY['organic','ads','referral','partner'])[((i - 1) % 4) + 1],
        'newsletter', (i % 3 <> 0),
        'persona', (ARRAY['prático','entusiasta','premium','caçador_de_ofertas'])[((i - 1) % 4) + 1]
    )
FROM generate_series(1, 80) AS g(i);

-- Produtos: 48 registros.
INSERT INTO products (id, category_id, supplier_id, sku, name, price, cost, stock, active, attributes, tags)
SELECT
    i,
    ((i - 1) % 8) + 1,
    ((i - 1) % 10) + 1,
    'SKU-' || lpad(i::text, 4, '0'),
    (ARRAY['Eletrônico','Item para Casa','Material de Escritório','Artigo Esportivo','Livro','Game','Produto de Beleza','Acessório'])[((i - 1) % 8) + 1] || ' ' || lpad(i::text, 2, '0'),
    round((19.90 + ((i * 37) % 850) + ((i % 7) * 0.73))::numeric, 2),
    round(((19.90 + ((i * 37) % 850) + ((i % 7) * 0.73)) * (0.48 + ((i % 5) * 0.04)))::numeric, 2),
    8 + ((i * 13) % 95),
    (i % 13 <> 0),
    jsonb_build_object(
        'color', (ARRAY['preto','branco','azul','verde','vermelho','cinza'])[((i - 1) % 6) + 1],
        'warranty_months', (ARRAY[3,6,12,18,24])[((i - 1) % 5) + 1],
        'weight_kg', round((0.2 + ((i * 17) % 80) / 10.0)::numeric, 1)
    ),
    ARRAY[
        (ARRAY['novo','popular','premium','econômico'])[((i - 1) % 4) + 1],
        (ARRAY['online','loja','presente','essencial'])[((i - 1) % 4) + 1]
    ]::text[]
FROM generate_series(1, 48) AS g(i);

-- Pedidos: 360 registros distribuídos entre 2024 e 2025.
INSERT INTO orders (id, customer_id, salesperson_id, order_date, status, channel, shipping_city, shipping_state, discount, freight)
SELECT
    i,
    ((i * 7 - 1) % 80) + 1,
    6 + ((i * 5) % 4),
    TIMESTAMP '2024-01-02 08:00:00' + ((i * 47) % 715) * INTERVAL '1 day' + ((i * 37) % 600) * INTERVAL '1 minute',
    CASE
        WHEN i % 17 = 0 THEN 'cancelled'
        WHEN i % 13 = 0 THEN 'pending'
        WHEN i % 7 = 0 THEN 'paid'
        WHEN i % 5 = 0 THEN 'shipped'
        ELSE 'delivered'
    END,
    (ARRAY['web','mobile','store','marketplace'])[((i - 1) % 4) + 1],
    c.city,
    c.state,
    CASE WHEN i % 9 = 0 THEN 0.10 WHEN i % 5 = 0 THEN 0.05 ELSE 0 END,
    round((8 + ((i * 11) % 37) + (i % 4) * 0.55)::numeric, 2)
FROM generate_series(1, 360) AS g(i)
JOIN customers c ON c.id = (((i * 7 - 1) % 80) + 1);

-- Itens: de 2 a 5 produtos por pedido.
INSERT INTO order_items (order_id, product_id, quantity, unit_price, discount)
SELECT
    o.id,
    p.id,
    1 + ((o.id + x.n) % 5)::integer,
    p.price,
    CASE WHEN (o.id + x.n) % 11 = 0 THEN 0.15 WHEN x.n = 4 THEN 0.05 ELSE 0 END
FROM orders o
CROSS JOIN LATERAL generate_series(1, 2 + (o.id % 4)::integer) AS x(n)
JOIN products p ON p.id = (((o.id * 11 + x.n * 7 - 1) % 48) + 1)
ON CONFLICT (order_id, product_id) DO NOTHING;

-- Pagamentos, calculados a partir dos itens.
INSERT INTO payments (order_id, method, paid_at, amount, status, installments)
SELECT
    o.id,
    (ARRAY['pix','credit_card','debit_card','bank_slip'])[((o.id - 1) % 4) + 1],
    CASE WHEN o.status = 'pending' THEN NULL ELSE o.order_date + INTERVAL '2 hours' END,
    round((SUM(oi.line_total) * (1 - o.discount) + o.freight)::numeric, 2),
    CASE
        WHEN o.status = 'cancelled' THEN 'refunded'
        WHEN o.status = 'pending' THEN 'pending'
        WHEN o.id % 29 = 0 THEN 'failed'
        ELSE 'approved'
    END,
    CASE WHEN o.id % 4 = 1 THEN 1 ELSE 1 + (o.id % 6)::integer END
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
GROUP BY o.id;

-- Avaliações: 180 pares cliente/produto únicos.
INSERT INTO reviews (customer_id, product_id, rating, comment, created_at)
SELECT
    1 + ((i * 17 - 1) % 80),
    1 + ((i * 13 - 1) % 48),
    1 + (i % 5),
    CASE
        WHEN i % 5 = 0 THEN 'Excelente custo-benefício.'
        WHEN i % 5 = 1 THEN 'Atendeu ao esperado.'
        WHEN i % 5 = 2 THEN 'Produto bom, entrega poderia melhorar.'
        WHEN i % 5 = 3 THEN 'Qualidade acima da média.'
        ELSE 'Experiência razoável.'
    END,
    TIMESTAMP '2024-02-01 10:00:00' + (i * 3) * INTERVAL '1 day'
FROM generate_series(1, 180) AS g(i)
ON CONFLICT (customer_id, product_id) DO NOTHING;

-- Tickets de suporte: 140 registros.
INSERT INTO support_tickets (customer_id, assigned_to, category, priority, status, opened_at, closed_at)
SELECT
    1 + ((i * 19 - 1) % 80),
    15 + ((i - 1) % 3),
    (ARRAY['delivery','payment','product','return','account'])[((i - 1) % 5) + 1],
    (ARRAY['low','medium','high','urgent'])[((i - 1) % 4) + 1],
    CASE WHEN i % 9 = 0 THEN 'open' WHEN i % 7 = 0 THEN 'in_progress' WHEN i % 3 = 0 THEN 'closed' ELSE 'resolved' END,
    TIMESTAMP '2024-03-01 09:00:00' + (i * 4) * INTERVAL '1 day',
    CASE
        WHEN i % 9 = 0 OR i % 7 = 0 THEN NULL
        ELSE TIMESTAMP '2024-03-01 09:00:00' + (i * 4) * INTERVAL '1 day' + (4 + (i % 72)) * INTERVAL '1 hour'
    END
FROM generate_series(1, 140) AS g(i);

-- Movimentações de estoque: 300 registros.
INSERT INTO inventory_movements (product_id, movement_type, quantity, occurred_at, note)
SELECT
    1 + ((i * 7 - 1) % 48),
    CASE WHEN i % 10 = 0 THEN 'ADJUSTMENT' WHEN i % 3 = 0 THEN 'IN' ELSE 'OUT' END,
    CASE
        WHEN i % 10 = 0 THEN CASE WHEN i % 20 = 0 THEN -2 ELSE 3 END
        WHEN i % 3 = 0 THEN 10 + (i % 25)
        ELSE -(1 + (i % 7))
    END,
    TIMESTAMP '2024-01-01 07:00:00' + (i * 2) * INTERVAL '1 day',
    CASE WHEN i % 10 = 0 THEN 'Ajuste de inventário' WHEN i % 3 = 0 THEN 'Entrada de fornecedor' ELSE 'Saída operacional' END
FROM generate_series(1, 300) AS g(i);

-- Índices úteis para os estudos de performance.
CREATE INDEX idx_customers_state ON customers(state);
CREATE INDEX idx_customers_segment ON customers(segment);
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_supplier ON products(supplier_id);
CREATE INDEX idx_orders_customer_date ON orders(customer_id, order_date DESC);
CREATE INDEX idx_orders_status_date ON orders(status, order_date);
CREATE INDEX idx_order_items_product ON order_items(product_id);
CREATE INDEX idx_reviews_product_rating ON reviews(product_id, rating);
CREATE INDEX idx_tickets_status_priority ON support_tickets(status, priority);
CREATE INDEX idx_inventory_product_date ON inventory_movements(product_id, occurred_at);
CREATE INDEX idx_products_attributes_gin ON products USING gin(attributes);
CREATE INDEX idx_products_tags_gin ON products USING gin(tags);

-- Views prontas para consultas intermediárias e avançadas.
CREATE VIEW vw_order_totals AS
SELECT
    o.id AS order_id,
    o.customer_id,
    o.salesperson_id,
    o.order_date,
    o.status,
    o.channel,
    round((SUM(oi.line_total) * (1 - o.discount) + o.freight)::numeric, 2) AS total_amount,
    SUM(oi.quantity)::integer AS total_units,
    COUNT(*)::integer AS item_lines
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
GROUP BY o.id;

CREATE VIEW vw_customer_summary AS
SELECT
    c.id AS customer_id,
    c.name,
    c.segment,
    c.state,
    COUNT(v.order_id)::integer AS order_count,
    COALESCE(round(SUM(v.total_amount)::numeric, 2), 0) AS lifetime_value,
    MAX(v.order_date) AS last_order_at
FROM customers c
LEFT JOIN vw_order_totals v ON v.customer_id = c.id AND v.status <> 'cancelled'
GROUP BY c.id;

-- Ajusta as sequences após inserts com IDs explícitos.
SELECT setval(pg_get_serial_sequence('departments','id'),      (SELECT max(id) FROM departments));
SELECT setval(pg_get_serial_sequence('employees','id'),        (SELECT max(id) FROM employees));
SELECT setval(pg_get_serial_sequence('customers','id'),        (SELECT max(id) FROM customers));
SELECT setval(pg_get_serial_sequence('categories','id'),       (SELECT max(id) FROM categories));
SELECT setval(pg_get_serial_sequence('suppliers','id'),        (SELECT max(id) FROM suppliers));
SELECT setval(pg_get_serial_sequence('products','id'),         (SELECT max(id) FROM products));
SELECT setval(pg_get_serial_sequence('orders','id'),           (SELECT max(id) FROM orders));

COMMIT;

-- Checagem rápida ao final.
SELECT 'departments' AS table_name, count(*) AS rows FROM departments
UNION ALL SELECT 'employees', count(*) FROM employees
UNION ALL SELECT 'customers', count(*) FROM customers
UNION ALL SELECT 'products', count(*) FROM products
UNION ALL SELECT 'orders', count(*) FROM orders
UNION ALL SELECT 'order_items', count(*) FROM order_items
UNION ALL SELECT 'payments', count(*) FROM payments
UNION ALL SELECT 'reviews', count(*) FROM reviews
UNION ALL SELECT 'support_tickets', count(*) FROM support_tickets
UNION ALL SELECT 'inventory_movements', count(*) FROM inventory_movements
ORDER BY table_name;
